import localFont from "next/font/local";
import "./globals.css";
import NavigationMenuDemo from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "SCEIC - 2025",
  description: "Generated by HITK",
  icons: {
    icon: 'https://res.cloudinary.com/dmbxx03vp/image/upload/v1732252587/logo_iyezkl.png',
    apple: 'https://res.cloudinary.com/dmbxx03vp/image/upload/v1732252587/logo_iyezkl.png',
    shortcut: 'https://res.cloudinary.com/dmbxx03vp/image/upload/v1732252587/logo_iyezkl.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="theme-color" content="#1bf551" />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <NavigationMenuDemo /> 
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
