import localFont from "next/font/local";
import { Roboto_Slab } from 'next/font/google'
import "./globals.css";
import NavigationMenuDemo from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";

const inter = Roboto_Slab({ weight: ["400"], subsets: ["latin"] });

export const metadata = {
  title: "SCEIC - 2025",
  description: "Generated by HITK",
  icons: {
    icon: 'https://res.cloudinary.com/dmbxx03vp/image/upload/v1732252587/logo_iyezkl.png',
    apple: 'https://res.cloudinary.com/dmbxx03vp/image/upload/v1732252587/logo_iyezkl.png',
    shortcut: 'https://res.cloudinary.com/dmbxx03vp/image/upload/v1732252587/logo_iyezkl.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="theme-color" content="#1bf551" />

      <body
        className={inter.className}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <NavigationMenuDemo /> 
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
